{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aeman.fullname" . }}
  namespace: {{ include "aeman.namespace" . }}
  labels:
    {{- include "aeman.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aeman.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
