apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aeman.fullname" . }}-config
  namespace: {{ include "aeman.namespace" . }}
  labels:
    {{- include "aeman.labels" . | nindent 4 }}
type: Opaque
stringData:
  AEMAN_GITHUB_CLIENT_ID: {{ .Values.config.githubClientId | quote }}
  AEMAN_GITHUB_CLIENT_SECRET: {{ .Values.config.githubClientSecret | quote }}
  AEMAN_BASE_URL: {{ .Values.config.baseUrl | quote }}
  AEMAN_SCOPES: {{ .Values.config.scopes | quote }}
  AEMAN_OWNER: {{ .Values.config.owner | quote }}
  AEMAN_PROJECT: {{ .Values.config.project | quote }}
  AEMAN_LOCK_BOARD: {{ .Values.config.lockBoard | quote }}
  AEMAN_SESSION_FILE: {{ printf "%s/registry.json" .Values.persistence.mountPath | quote }}
